name: user_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  lottie: ^2.0.0
  riverpod: ^1.0.3
  change_app_package_name: ^1.1.0

  
dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/animations/loader_animation.json
    - assets/icon/icon.png
    
flutter_intl:
  enabled: true
  main_locale: en
  class_name: I18n
